src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/community/controllers/CommunityController.java, src/main/java/com/sublinks/sublinksapi/community/models/CommunitySearchCriteria.java, src/main/java/com/sublinks/sublinksapi/community/repositories/CommunityRepository.java, src/main/java/com/sublinks/sublinksapi/community/repositories/CommunityRepositoryImpl.java, src/main/java/com/sublinks/sublinksapi/community/repositories/CommunitySearchRepository.java
This commit introduces a new model, CommunitySearchCriteria that is used to filter out communities by specific criteria in the list API. It also includes the modification of CommunityRepository to use this new search criteria and the implementation of these changes in CommunityController. For the new search criteria, a new file, CommunitySearchRepository, was added to provide more flexible search options. Lastly, some code formatting and clean up has been done for better readability.
=> Add community search criteria for list API

src/main/java/com/sublinks/sublinksapi/utils/KeyGeneratorUtil.java, src/main/java/com/sublinks/sublinksapi/utils/MentionUtils.java, src/main/java/com/sublinks/sublinksapi/utils/PaginationUtils.java, src/main/java/com/sublinks/sublinksapi/utils/SiteMetadataUtil.java, src/main/java/com/sublinks/sublinksapi/utils/SlugUtil.java, src/main/java/com/sublinks/sublinksapi/utils/UrlUtil.java
My first pr, so I wanted to keep it with a small scope. Working through #15 bit by bit. If there is a problem please let me know.
=> Added JavaDoc to utils package.

src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/image/controllers/ImageController.java
This seemed like an easy fix so I went ahead and implemented it. I'm just making the proper calls to the pict-rs API and forwarding the status and body, exactly how the Lemmy API already does it. I've already tested it and it works like a charm.
The Swagger Doc specifies that this function responds with a 200 status, but pict-rs responds a 204 status, To align with our API documentation, I've adjusted the implementation to transform a 204 response from pict-rs to a 200 status code
=> Implement delete Method in ImageController for Image Deletion

src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/user/services/LemmyPersonService.java
Extended LemmyPersonService to retrieve several person-related entities. Added methods for retrieving all posts by a specific person, communities moderated by a person, and all comments made by a user. This update intends to provide a comprehensive view of a user's activities.
=> Add functionality to LemmyPersonService

docs/docker-compose.yml, src/main/java/com/sublinks/sublinksapi/queue/QueueConfig.java
- Adds a default of an empty string to the routing key variable
=> fix: fixes a default var for routing key

src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/user/controllers/UserController.java, src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/user/models/ExportSettingsResponse.java, src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/user/models/ImportSettings.java, src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/user/models/SuccessResponse.java, src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/user/models/UserExportSettings.java
=> Implemented Import and Export

build.gradle, src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/errorhandler/RestExceptionHandler.java, src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/user/controllers/UserAuthController.java, src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/user/mappers/LocalUserMapper.java, src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/user/models/UpdateTotp.java, src/main/java/com/sublinks/sublinksapi/person/dto/Person.java, src/main/java/com/sublinks/sublinksapi/utils/TotpUtil.java, src/main/java/com/sublinks/sublinksapi/utils/models/LemmyException.java, src/main/resources/db/migration/V20231003__Create_initial_entity_tables.sql
I have to test it, will do it tomorrow.
closes #102
=> feat: Implemented totp

src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/user/mappers/PersonMapper.java, src/main/java/com/sublinks/sublinksapi/person/dto/Person.java, src/main/java/com/sublinks/sublinksapi/person/services/PersonService.java, src/main/java/com/sublinks/sublinksapi/utils/BaseUrlUtil.java, src/main/resources/db/migration/V20231003__Create_initial_entity_tables.sql, src/main/resources/db/migration/V20240127__Add_actor_id_person_table.sql
resolves issue where posts hangs on loading state
=> feat: fixes actor_id issue with user

docs/docker-compose.yml
Fixes based on discussion in Matrix dev room
=> Fix docker compose file

src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/comment/controllers/CommentController.java, src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/comment/controllers/CommentModActionsController.java, src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/community/controllers/CommunityController.java, src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/post/controllers/PostController.java, src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/post/controllers/PostModActionsController.java, src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/privatemessage/controllers/PrivateMessageController.java, src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/user/controllers/UserController.java, src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/utils/PaginationControllerUtils.java
This commit adds the PaginationControllerUtils, which manages pagination-related aspects in various kinds of "get" requests. This utility class effectively addresses the issue of null or inappropriate page or limit values by providing a default value. It enhances the readability of the code by implementing more easily understandable methods, and also secures value boundaries to prevent potential errors.
=> Implement PaginationControllerUtils for better code readability

docs/docker-compose.yml, src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/community/controllers/CommunityOwnerController.java, src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/user/controllers/UserAuthController.java, src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/user/controllers/UserController.java, src/main/java/com/sublinks/sublinksapi/federation/enums/ActorType.java, src/main/java/com/sublinks/sublinksapi/federation/enums/RoutingKey.java, src/main/java/com/sublinks/sublinksapi/federation/models/Actor.java, src/main/java/com/sublinks/sublinksapi/queue/config/QueueConfig.java, src/main/resources/application.properties
- Implements Actor model and enums 
- Sends Actor message to consumer for federation depending on whether federation is enabled
=> feat: #148: Actor created message to federation

src/main/java/com/sublinks/sublinksapi/slurfilter/services/SlurFilterService.java, src/test/java/com/sublinks/sublinksapi/slurfilter/services/SlurFilterServiceUnitTests.java
=> Fixed slur replace test and service

src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/comment/controllers/CommentController.java, src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/post/controllers/PostController.java, src/main/java/com/sublinks/sublinksapi/authorization/enums/RolePermission.java, src/main/java/com/sublinks/sublinksapi/person/services/PersonService.java
=> Fixed the authorizing errors on the vote endpoints

lombok.config, src/main/java/com/sublinks/sublinksapi/customemoji/services/CustomEmojiService.java, src/test/java/com/sublinks/sublinksapi/customemoji/dto/CustomEmojiKeywordTest.java, src/test/java/com/sublinks/sublinksapi/customemoji/dto/CustomEmojiTest.java, src/test/java/com/sublinks/sublinksapi/customemoji/services/CustomEmojiServiceTest.java
This PR adds testing to the CustomEmoji package
=> 241-Custom-Emoji-Tests

src/main/resources/db/migration/V20231006__Create_foreign_key_references.sql
=> Fixed Migration again

src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/authentication/JwtFilter.java, src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/common/controllers/AbstractLemmyApiController.java
=> #301 Resolved issue causing new site setup to fail

.github/CODEOWNERS, .github/dependabot.yml, .gitmodules, README.md
- Gradle dependencies maintenance in Dependabot
- Daily update schedule for Git submodules in Dependabot
- Add CODEOWNERS file
- Updated README with Docker setup and run instructions
- Local Development link from README
- Added `docker` submodule with specific commit reference
=> Centralized docker compose

src/main/java/com/sublinks/sublinksapi/post/listeners/PostLikeCreatedListener.java
=> #311: Fixed like aggregation calculation

src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/comment/controllers/CommentController.java, src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/post/controllers/PostOwnerController.java
Improved how language is handled by setting a default if language is not specified and providing an exception for language not found. Also, the code formatting in several instances has been cleaned up to make it more readable and maintainable.
=> Update language handling and clean up formatting

src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/site/controllers/SiteController.java, src/main/java/com/sublinks/sublinksapi/community/entities/Community.java, src/main/java/com/sublinks/sublinksapi/person/entities/Person.java, src/main/java/com/sublinks/sublinksapi/post/entities/Post.java
=> #368 Fixed DB loading time and column count error

src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/user/controllers/UserController.java
Close https://github.com/sublinks/sublinks-api/issues/374
=> change http status of exception to NotFound when person is not found in api call

src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/authentication/JwtFilter.java, src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/image/controllers/ImageController.java, src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/image/models/Image.java, src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/image/models/ImagesResponse.java, src/main/java/com/sublinks/sublinksapi/authorization/enums/RolePermissionMediaTypes.java, src/main/java/com/sublinks/sublinksapi/authorization/services/InitialRoleSetupService.java, src/main/java/com/sublinks/sublinksapi/community/services/CommunityService.java, src/main/java/com/sublinks/sublinksapi/media/entities/Media.java, src/main/java/com/sublinks/sublinksapi/media/respositories/MediaRepository.java, src/main/java/com/sublinks/sublinksapi/media/services/MediaService.java, src/main/resources/db/migration/V20231003__Create_initial_entity_tables.sql, src/main/resources/db/migration/V20231006__Create_foreign_key_references.sql
=> #201 Media upload person logging

src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/post/controllers/PostOwnerController.java, src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/post/models/CreatePost.java
closes #385 
Fixes that post creation doesnt require a url.
=> Fixes 385 - Post creation without url

src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/post/controllers/PostController.java
This commit modifies the PostController to enforce REST standards more strictly and improve code readability. The 'markAsRead' endpoint was removed and the code base was refactored with an emphasis on clarity and order. The handling of community posts was also improved.
Fixes #391
=> Refactor PostController and remove 'markAsRead' functionality

src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/post/controllers/PostController.java
=> Fixed that the type is optional

src/main/java/com/sublinks/sublinksapi/comment/services/CommentService.java
The changes include breaking down longer lines of codes into multiple lines to improve code readability. This includes method calls and error handling. Also, an update has been added to increment the children count when a comment is created under another comment.
=> Refactor CommentService for improved readability

src/main/java/com/sublinks/sublinksapi/federation/enums/RoutingKey.java, src/main/java/com/sublinks/sublinksapi/federation/listeners/CommentCreateListener.java, src/main/java/com/sublinks/sublinksapi/federation/models/Comment.java, src/test/java/com/sublinks/sublinksapi/federation/CommentCreateUnitTests.java
- Adds listener for comment creation
- Sends to consumer for federation
=> feat/145: add comment messages sent to fed

src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/search/controllers/SearchController.java, src/main/java/com/sublinks/sublinksapi/search/services/SearchService.java, src/test/java/com/sublinks/sublinksapi/search/services/SearchServiceTests.java
Updated SearchService.java's search methods logic to include adjusted pagination and sorting options. The changes ensure correct page numbering and maximum page size restrictions. Furthermore, extensive inline documentation has been added for better code readability and understanding.
Fixes #424
=> Improve search service methods with pagination and sorting
