sublinks/sublinks-api

src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/community/controllers/CommunityOwnerController.java
src/main/java/com/sublinks/sublinksapi/community/repositories/CommunityRepository.java

This fixes a bug in which users are able to create communities when a local community with the same url already exists.

Prevent creation of duplicate communities

---

src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/authentication/JwtFilter.java
src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/site/controllers/SiteController.java

Expanded the JWT authentication method in JwtFilter to also search for JWT tokens in the cookies if it is not found in the "Authorization" header of the request. A token is assigned either from the header or from the cookies, depending on which contains the JWT. Also removed unnecessary import in the SiteController class.

Modify JWT authentication to attain token from cookies

---

src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/user/controllers/UserAuthController.java
src/main/java/com/sublinks/sublinksapi/instance/services/InstanceConfigService.java
src/main/java/com/sublinks/sublinksapi/person/listeners/InstanceConfigUpdatedListener.java
src/main/java/com/sublinks/sublinksapi/person/repositories/CaptchaRepository.java
src/main/java/com/sublinks/sublinksapi/person/scheduling/CaptchaScheduler.java
src/main/java/com/sublinks/sublinksapi/person/services/CaptchaService.java

This update refactors the Captcha service and introduces an added feature to adjust complexity levels. The noise producers and captcha renderers have been revised to provide different levels of difficulty. The configuration updates will permit setting captcha difficulty - impacting the generation process. Significant enhancements have also been made to the 'captcha' table in the database to ensure efficient functioning and error handling during the registration process. Additionally, an unmapped target policy has been included to prevent unexpected mapping processes.

Refactor Captcha service and introduce complexity level setting

---

src/main/java/com/sublinks/sublinksapi/utils/SlugUtil.java
src/test/java/com/sublinks/sublinksapi/utils/SlugUtilUnitTest.java

Changed replace with replaceAll in SlugUtils. Enabled disabled test.

Non-alphanumeric characters are not removed when converting a string to a slug #173

---

src/main/java/com/sublinks/sublinksapi/utils/UrlUtil.java
src/test/java/com/sublinks/sublinksapi/utils/UrlUtilUnitTests.java

closes #168, implements suggested fix and enables the tests that were failing before this change

fix: return nulls instead of empty strings from urlutil

---

src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/authentication/JwtFilter.java
src/main/java/com/sublinks/sublinksapi/person/config/CaptchaConfiguration.java
src/main/java/com/sublinks/sublinksapi/person/config/UserDataConfig.java
src/main/java/com/sublinks/sublinksapi/person/dto/Person.java
src/main/java/com/sublinks/sublinksapi/person/dto/UserData.java
src/main/java/com/sublinks/sublinksapi/person/events/UserDataCreatedEvent.java
src/main/java/com/sublinks/sublinksapi/person/events/UserDataCreatedPublisher.java
src/main/java/com/sublinks/sublinksapi/person/events/UserDataDeletedEvent.java
src/main/java/com/sublinks/sublinksapi/person/events/UserDataDeletedPublisher.java
src/main/java/com/sublinks/sublinksapi/person/repositories/UserDataRepository.java
src/main/java/com/sublinks/sublinksapi/person/scheduling/UserDataScheduler.java
src/main/java/com/sublinks/sublinksapi/person/services/UserDataService.java
src/main/resources/application.properties
src/main/resources/db/migration/V20231003__Create_initial_entity_tables.sql

Added a new table `user_data` to store user information including IPs, along with services, configurations, and repositories to support the function. This feature is opt-in and can be activated by changing the `sublinks.save_user_ips` setting in `application.properties`. This is a privacy concern as it stores user IPs, thus is disabled by default. Therefore, properly inform the user as per your privacy policy and/or local laws.
closes #153

Add user IP tracking feature

---

build.gradle

Jacoco Test Report Coverage Plugin (https://docs.gradle.org/current/userguide/jacoco_plugin.html)
With the issues for unit testing (#246 #245 #244 #243 #242 #241 #240 #239 #238) that have been added, it may be good to add a test coverage report, if only for informational cases. This PR does not add any requirements for code coverage for builds.
This can also be rolled into one of the PRs for Unit testing as well or closed if it's been discussed already (I can't seem to find mention of the plugin in anything closed)

Added Jacoco Test Coverage Report

---

.github/workflows/gradle.yml
Dockerfile
build.gradle

This PR changes from using the Gradle task `bootBuildImage` to use a custom Dockerfile. This is needed as the buildpacks used by SpringBoot do not support generating arm64 images. I've copied the workflow content from the federation service here so that the docker image generation is the same for both services. Additionally, I needed to disable the generation of the "-plain.jar" file to avoid confusion when building the docker image. The difference between the "-plain.jar" file and the other jar file is that the "plain" one contains only the compiled code from the service. It doesn't contain any of the libraries required to actually run the service. Since it is unlikely we would need this for anything, I believe it is fine to disable it (normally it's used when generating a "native …

Change to use Dockerfile to build multi-arch images

---

src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/authentication/JwtFilter.java

The JwtFilter has been updated to catch SignatureExceptions alongside ExpiredJwtExceptions. This provides enhanced error handling in this area. Additionally, to provide more detailed feedback on errors, the response now sends an "invalid_token" message when these exceptions are thrown.
closes #274

Add handling for SignatureException in JwtFilter

---

src/main/java/com/sublinks/sublinksapi/person/config/UserDataConfig.java
src/main/java/com/sublinks/sublinksapi/person/entities/PersonEmailVerification.java
src/main/java/com/sublinks/sublinksapi/person/repositories/UserDataRepository.java
src/main/java/com/sublinks/sublinksapi/person/services/PersonEmailVerificationService.java
src/main/java/com/sublinks/sublinksapi/person/services/UserDataService.java
src/main/resources/application.properties
src/main/resources/db/migration/V20231003__Create_initial_entity_tables.sql

This update modifies the handling of user data in the PersonEmailVerification service, UserData service and UserData repository. User data (like IP address and user agent) is now saved or not based on the "sublinks.save_user_data" configuration property. This adds an extra layer of control and privacy customization to the application. Database schema and queries have been revised to accommodate this functionality.

Fixed that userdata is correctly saved only if the config is set.

---

src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/comment/controllers/CommentController.java
src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/privatemessage/controllers/PrivateMessageController.java
src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/user/controllers/UserAuthController.java

Validation annotations (@Valid) were added to the request bodies in delete, saveForLater, and verifyEmail methods in CommentController, UserAuthController respectively. A long line of code in PrivateMessageController was also split for better readability.

Add request validation to various methods

---

src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/comment/controllers/CommentController.java
src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/comment/mappers/CommentReplyMapper.java
src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/comment/models/GetReplies.java
src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/privatemessage/controllers/PrivateMessageController.java
src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/privatemessage/models/GetPrivateMessages.java
src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/user/controllers/UserController.java
src/main/java/com/sublinks/sublinksapi/comment/entities/CommentReply.java
src/main/java/com/sublinks/sublinksapi/comment/repositories/CommentReplyRepository.java
src/main/java/com/sublinks/sublinksapi/person/entities/UserData.java
src/main/java/com/sublinks/sublinksapi/person/repositories/PersonMentionRepository.java
src/main/java/com/sublinks/sublinksapi/privatemessages/models/MarkAllAsReadResponse.java
src/main/java/com/sublinks/sublinksapi/privatemessages/models/PrivateMessageSearchCriteria.java
src/main/java/com/sublinks/sublinksapi/privatemessages/repositories/PrivateMessageRepository.java
src/main/java/com/sublinks/sublinksapi/privatemessages/repositories/PrivateMessageRepositoryImpl.java
src/main/java/com/sublinks/sublinksapi/privatemessages/services/PrivateMessageService.java
src/main/resources/db/migration/V20231003__Create_initial_entity_tables.sql

Changed nullable property for ip_address and altered boolean field in UserDate and CommentReply entities respectively. Implemented 'mark all as read' functionality in UserController and PrivateMessageService which marks all private messages, comment replies, and person mentions as read. Adjusted queries in relevant repositories to support this change. Numerous minor adjustments were made across various other classes to enhance code readability and maintain consistency.
closes #322

Update entity properties and add mark all as read functionality

---

README.md

The upstream uses `yml` not `yaml`. This fixes that.

Fix typo in README for Docker command.

---

.github/CODEOWNERS
SECURITY.md

Add a SECURITY.md file to provide guidelines for reporting security issues. This will help in the responsible disclosure of security bugs by detailing the process for reporting vulnerabilities. It includes a link to the GitHub Security Advisory for ease of access and ensures contributors are informed about the handling of their reports.

Add SECURITY.md to outline security issue reporting

---

src/test/java/com/sublinks/sublinksapi/search/services/SearchServiceTests.java

fixes #246 
-Added unit testing to the search package

#246-added unit test to search package

---

src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/comment/controllers/CommentController.java
src/main/java/com/sublinks/sublinksapi/comment/entities/Comment.java
src/main/java/com/sublinks/sublinksapi/comment/models/CommentSearchCriteria.java
src/main/java/com/sublinks/sublinksapi/comment/repositories/CommentRepositoryImpl.java

The CommentSearchCriteria now includes the option to search for comments based on their parent comment. This added functionality allows for more specific and organized comment retrieval, improving data filtering mechanisms. Any code calling this search function can now also filter comments by their parent comment.

Add search by parent comment functionality

---

build.gradle

Per https://github.com/flyway/flyway/issues/3780 v10 of Flyway split out into modules. We already have the mysql module, but when the database was switched to Postgres we never added the postgres module

Add org.flywaydb:flyway-database-postgresql dependency

---

src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/authentication/config/SecurityConfig.java

The changes in this commit involve deactivating the CSRF protection in the SecurityConfig.java file. This action simplifies the configuration while retaining the necessary permissions and session management. The code also becomes slightly

Disable CSRF protection in SecurityConfig

---

src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/admin/controllers/AdminController.java
src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/authentication/config/SecurityConfig.java
src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/comment/controllers/CommentController.java
src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/comment/controllers/CommentModActionsController.java
src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/community/controllers/CommunityOwnerController.java
src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/image/controllers/ImageController.java
src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/post/controllers/PostOwnerController.java
src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/user/controllers/UserAuthController.java
src/main/java/com/sublinks/sublinksapi/authorization/services/AclService.java
src/main/java/com/sublinks/sublinksapi/authorization/services/RolePermissionService.java

The code has been updated to add permission checks before every action on entities to enhance security. This ensures actions can only be performed by authorized users. Furthermore, some code blocks have been refactored to improve readability and maintainability. For example, the `@ApiResponses` annotations have been reformatted for better understandability.

Implemented Community Ban logic and Improved Handling of ACL Service

---

src/main/java/com/sublinks/sublinksapi/post/services/PostSearchQueryService.java

Previously, the pagination logic treated negative and zero page indices the same, defaulting to 0. This change ensures that the first page starts from 1, aligning with typical pagination conventions.

Fix pagination to start from page 1 instead of 0.
